name: Test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox-gh-actions

    - run: env | sort

    - name: Setup test suite
      run: python -m tox r -vv --notest

    - name: Run test suite
      run: python -m tox r --skip-pkg-install
      env:
        PYTEST_ADDOPTS: "-vv --durations=10"

  extra:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type:
        - flake8
        - black
        - doctests
        - cov

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install tox
    - run: python -m tox -e ${{ matrix.test-type }}
    - run: ./.tox/cov/bin/coverage html
      # Run even if previous step failed but only if we are testing coverage
      if: ${{ always() && matrix.test-type == 'cov' }}
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage_html/
      if: ${{ always() && matrix.test-type == 'cov' }}

  'py36':
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: '3.6'
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: python -m pip install tox
    - run: python -m tox -e 36
